<a href="https://colab.research.google.com/github/moustafa-7/PyTorch-Course/blob/master/PyTorch_Matrix_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import numpy as np

In [7]:
arr =  [[1,2],[3,4]]
print(arr)

[[1, 2], [3, 4]]


In [4]:
np.array(arr)

array([[1, 2],
       [3, 4]])

In [0]:
import torch

In [8]:
torch.Tensor(arr)

tensor([[1., 2.],
        [3., 4.]])

In [9]:
np.ones((2,2))


array([[1., 1.],
       [1., 1.]])

In [10]:
torch.ones((2,2))

tensor([[1., 1.],
        [1., 1.]])

In [12]:
np.random.rand(2,2)

array([[0.18628319, 0.63092597],
       [0.99129139, 0.99828323]])

In [13]:
  torch.rand(2,2)

tensor([[0.5174, 0.5935],
        [0.9785, 0.0157]])

## Seeds for Reproducability

In [14]:
np.random.seed(0)
np.random.rand(2,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [16]:
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [17]:
torch.rand(2,2)

tensor([[0.3074, 0.6341],
        [0.4901, 0.8964]])

## Seed are for CPU

In [19]:
if torch.cuda.is_available():
  print(torch.cuda.is_available())
  torch.cuda.manual_seed_all(0)

True


In [0]:
torch_tensor = torch.ones(2,2)

In [21]:
type(torch_tensor)

torch.Tensor

In [0]:
torch_np = torch_tensor.numpy()

In [23]:
type(torch_np)

numpy.ndarray

Tensors on CPU to GPU

In [0]:
tensor_cpu = torch.ones(2,2)  # by default it is on the CPU

In [0]:
if torch.cuda.is_available():
  tensor_cpu.cuda()

## Tensor operations

In [27]:
a = torch.ones(2,2)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [28]:
print(a.size())

torch.Size([2, 2])


In [34]:
a.view(4)   # view changes the size of the tensor only the view

tensor([1., 1., 1., 1.])

In [33]:
print(a)

tensor([[1., 1.],
        [1., 1.]])


## Element wise addition

In [0]:
b = torch.ones(2,2)

In [0]:
c = a + b

In [0]:
c= torch.add(a,b)

In [38]:
c

tensor([[2., 2.],
        [2., 2.]])

## Inplace addition

In [39]:
print("Old c tensor")
print(c)

Old c tensor
tensor([[2., 2.],
        [2., 2.]])


In [40]:
c.add_(a)

tensor([[3., 3.],
        [3., 3.]])

In [0]:
print('_'*60)

In [41]:
print(c)

tensor([[3., 3.],
        [3., 3.]])


## Element-Wise Multiplication

In [42]:
a = torch.ones(2,2)
print(a)
b = torch.zeros(2,2)
print(b)

tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])


In [43]:
a*b

tensor([[0., 0.],
        [0., 0.]])

In [45]:
a.mean()

tensor(1.)

# PyTorch Variables and Gradients

## Variables

In [0]:
from torch.autograd import Variable

In [48]:
a = Variable(torch.ones(2,2), requires_grad = True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [49]:
b = Variable(torch.ones(2,2), requires_grad = True)
print(a + b)
print(torch.add(a,b))

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)
tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


In [51]:
print(a*b)
print(torch.mul(a,b))

tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)
tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)


### Conclusion: Variables are treated like tensors

## Gradients

In [64]:
x = Variable(torch.ones(2), requires_grad = True)
x

TypeError: ignored

In [57]:
y = 5*(x+1)**2
y

tensor([20., 20.], grad_fn=<MulBackward0>)

In [0]:
o = 0.5 * torch.sum(y)

In [0]:
m = 0.5 * torch.sum(y)

In [0]:
m.backward(retain_graph=True)  

In [61]:
x.grad

tensor([10., 10.])